name: fantapi
description: FantAPI, pronounced as "fanta-pea", is an REST api for random fantasy entities. It is based on the [randpg](https://pub.dev/packages/randpg) package.
version: 1.0.0
repository: https://github.com/ItayElf/fantapi

environment:
  sdk: ^3.5.3

dependencies:
  args: ^2.4.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  randpg: ^0.12.0

dev_dependencies:
  http: ^1.1.0
  lints: ^4.0.0
  test: ^1.24.0
